services:
  koteamon:
    build:
      context: .
      dockerfile: Dockerfile
    image: koteamon:v.0.9.8
    container_name: koteamon
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - '7860:7860'
    platform: linux/amd64

    restart: unless-stopped
