services:
  koteamon:
    build:
      dockerfile: Dockerfile
      target: full
    image: koteamon:v.0.10.2
    container_name: koteamon
    env_file:
      - .env
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - '7860:7860'
    volumes:
      - ./ktem_app_data:/app/ktem_app_data
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    external: true
