[tool.uv.workspace]
members = [".", "libs/kotaemon", "libs/ktem"]

[build-system]
requires = ["setuptools >= 61.0", "wheel", "setuptools-git-versioning>=2.0,<3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false
packages.find.include = []

[tool.setuptools-git-versioning]
enabled = true
dev_template = "{tag}"
dirty_template = "{tag}"
tag_filter = "v?\\d+(\\.\\d+)*.*"

[project]
name = "kotaemon-app"
dynamic = ["version"]
requires-python = ">=3.10,<3.13"
description = "Kotaemon App"
dependencies = [
    "kotaemon[all]",
    "ktem",
    "elasticsearch>=8.17.0,<8.20",
    "unstructured[all-docs]>=0.16.20,<0.17",
    "sentry-sdk>=2.21.0",
    "psycopg2>=2.9.10",
    "lightrag-hku<=0.0.8",
    "aioboto3>=15.1.0",
    "nano-vectordb>=0.0.4.3",
    "pydantic<2.11"
]
authors = [
    { name = "@trducng", email = "john@cinnamon.is" },
    { name = "@lone17", email = "ian@cinnamon.is" },
    { name = "@taprosoft", email = "tadashi@cinnamon.is" },
    { name = "@cin-albert", email = "albert@cinnamon.is" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://cinnamon.github.io/kotaemon/"
Repository = "https://github.com/Cinnamon/kotaemon/"
Documentation = "https://cinnamon.github.io/kotaemon/"

[tool.codespell]
skip = "*.js,*.css,*.map"
# `llm` abbreviation for large language models
ignore-words-list = "llm,fo"
quiet-level = 3
check-filenames = ""

[tool.uv.sources]
kotaemon = { workspace = true }
ktem = { workspace = true }

[tool.isort]
known_first_party = ["kotaemon"]
