[tool.uv.workspace]
members = [".", "libs/kotaemon", "libs/ktem"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
elasticsearch = "^8.17.0"
lancedb = "^0.17.0"
tantivy = "^0.22.0"
numpy = "<2.0"
lightrag = "^0.1.0b6"
unstructured = {extras = ["all-docs"], version = "^0.16.20"}
sentry-sdk = "^2.21.0"
psycopg2 = "^2.9.10"

[dependency-groups]
full = [
  "torch >=2.7.0,<=2.8.0",
  "torchvision",
  "torchaudio",
  "psycopg2-binary >=2.8.0,<=2.9.10",
  "sentry-sdk >=2.34.0,<=2.35.1",
  "aioboto3",
  "nano-vectordb",
  "ollama >=0.5.0,<=0.5.3",
  "xxhash",
  "lightrag-hku >=0.0.6,<=0.0.8",
  "docling >=2.4.0,<=2.5.2",
  "unstructured-client >=0.25.0,<=0.27.0",
]

[build-system]
requires = ["setuptools >= 61.0", "wheel", "setuptools-git-versioning>=2.0,<3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false
packages.find.include = []

[tool.setuptools-git-versioning]
enabled = true
dev_template = "{tag}"
dirty_template = "{tag}"
tag_filter = "v?\\d+(\\.\\d+)*.*"

[project]
name = "kotaemon-app"
dynamic = ["version"]
requires-python = ">=3.10,<3.13"
description = "Kotaemon App"
dependencies = [
    "kotaemon[all]",
    "ktem",
    "elasticsearch>=8.17.0,<8.20",
    "unstructured[all-docs]>=0.16.20,<0.17",
    "sentry-sdk>=2.21.0",
    "psycopg2>=2.9.10",
    "lightrag-hku<=0.0.8",
    "aioboto3>=15.1.0",
    "nano-vectordb>=0.0.4.3",
    "pydantic<2.11"
]
authors = [
    { name = "@trducng", email = "john@cinnamon.is" },
    { name = "@lone17", email = "ian@cinnamon.is" },
    { name = "@taprosoft", email = "tadashi@cinnamon.is" },
    { name = "@cin-albert", email = "albert@cinnamon.is" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://cinnamon.github.io/kotaemon/"
Repository = "https://github.com/Cinnamon/kotaemon/"
Documentation = "https://cinnamon.github.io/kotaemon/"

[tool.codespell]
skip = "*.js,*.css,*.map"
# `llm` abbreviation for large language models
ignore-words-list = "llm,fo"
quiet-level = 3
check-filenames = ""

[tool.uv.sources]
kotaemon = { workspace = true }
ktem = { workspace = true }

[tool.isort]
known_first_party = ["kotaemon"]
